# Generated by Django 4.1.4 on 2022-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_alter_budgetapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
